name: Nats Blueprints CI and CD

on:
  push:
    paths:
      - 'nats/**'

  pull_request:
    paths:
      - 'nats/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: code-runner
  BUILD_ARG_VERSION_NAME: NATS_SERVER_VERSION
concurrency:
  group: nats-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nats_server_version: [2.10.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build nats:${{ matrix.nats_server_version }} image
        uses: ./.github/actions/docker-build
        with:
          context: ./nats
          dockerfile: ./nats/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}
          tag: nats-${{ matrix.nats_server_version }}
          push: false
          container-registry: ${{ env.REGISTRY }}
          build-arg-version-name: ${{ env.BUILD_ARG_VERSION_NAME }}
          build-arg-version-value: ${{ matrix.nats_server_version }}

  cd:
    runs-on: ubuntu-latest

    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}

    strategy:
      matrix:
        nats_server_version: [2.10.0]

    permissions:
      packages: write
      contents: read

    needs:
      - ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push nats:${{ matrix.nats_server_version }} image
        uses: ./.github/actions/docker-build
        with:
          context: ./nats
          dockerfile: ./nats/Dockerfile
          image-name: ${{ env.IMAGE_NAME }}
          tag: nats-${{ matrix.nats_server_version }}
          push: true
          container-registry: ${{ env.REGISTRY }}
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          build-arg-version-name: ${{ env.BUILD_ARG_VERSION_NAME }}
          build-arg-version-value: ${{ matrix.nats_server_version }}
